### PR TITLE
fixed issues encountered with the build

### PR DESCRIPTION
**Pull request by Xing-C**

### CODE REVIEW

**Comment by Xing-C** [comment]
but it

**Comment by SettingDust** [comment]
What's the issue?

EDIT: I see. I missed this PR. You have to register the key mapping. Just remove it not an option

**Comment by PlayfulPiano** [comment]
Is it possible to add the ability to rebind / remove the grave keybind for keymap?

**Comment by SettingDust** [comment]
> Is it possible to add the ability to rebind / remove the grave keybind for keymap?

This isn't place for issue. And can't understand what's `grave`

**Comment by PlayfulPiano** [comment]
> > Is it possible to add the ability to rebind / remove the grave keybind for keymap?
> 
> This isn't place for issue. And can't understand what's `grave`

the grave keybind (`, left of 1 and above tab), it's commonly used for veinminer mods so I wanted to remove keymap's binding to that key.

Also I was asking in here because this PR was working for me in forge 1.20.1 (I got it through the fabric discord).

**Comment by SettingDust** [comment]
> Also I was asking in here because this PR was working for me in forge 1.20.1 (I got it through the fabric discord).

Open issue

> the grave keybind (`, left of 1 and above tab), it's commonly used for veinminer mods so I wanted to remove keymap's binding to that key.

Should able to modify if it's using minecraft keybind

**Pull request closed without merging**
